# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/centos7"  #configuration du VM -> image geerlingguy/centos7"
  config.vm.network "private_network", type: "dhcp"

  config.ssh.insert_key = false #

  config.vm.synced_folder ".", "/vagrant", disabled: true #desactivé le dossier sychronisation

  config.vm.provider :virtualbox do |v|
    v.memory = 256 # ram 256 mg
    v.linked_clone = true
    v.memory = 2048
    v.cpus = 2

  end

# App serveur 1
  config.vm.define "app1" do |app|
    app.vm.hostname = "Thehive1"
    app.vm.network :private_network, ip: "192.168.60.4"

  end

# App serveur 2
  config.vm.define "app1.1" do |app|
    app.vm.hostname = "Thehive1"
    app.vm.network :private_network, ip: "192.168.60.5"

  end

# App serveur 3
  config.vm.define "app2" do |app|
    app.vm.hostname = "cortex-elk1"
    app.vm.network :private_network, ip: "192.168.60.6"

  end

  # App serveur 4
  config.vm.define "app2.2" do |app|
    app.vm.hostname = "cortex-elk2"
    app.vm.network :private_network, ip: "192.168.60.7"

  end

  # App serveur 5
  config.vm.define "app2.3" do |app|
    app.vm.hostname = "cortex-elk3"
    app.vm.network :private_network, ip: "192.168.60.8"

  end

  # App serveur 6
  config.vm.define "app3" do |app|
    app.vm.hostname = "cassandra1"
    app.vm.network :private_network, ip: "192.168.60.9"

  end

  # App serveur 7
  config.vm.define "app3.2" do |app|
    app.vm.hostname = "cassandra2"
    app.vm.network :private_network, ip: "192.168.60.10"

  end

  # App serveur 8
  config.vm.define "app3.3" do |app|
    app.vm.hostname = "cassandra3"
    app.vm.network :private_network, ip: "192.168.60.11"

  end
end

