
# -*- mode: ruby -*-
# vi: set ft=ruby :

 # serveur ekl1
Vagrant.configure("2") do |config|
  config.vm.define "srv-elk1" do |srvelk1|
    srvelk1.vm.box = "centos/7"
    srvelk1.vm.network "private_network", type: "dhcp"
    srvelk1.vm.hostname = "srv-elk1"
    srvelk1.vm.provider "virtualbox" do |v|
      v.name = "srv-elk1"
      v.memory = 2048
      v.cpus = 2
    end
    
    config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
    service sshd restart
  SHELL
  #jenkins.vm.provision "shell", path: "install_jenkins.sh"
end

 # serveur elk2
  config.vm.define "srv-elk2" do |srvelk2|
    srvelk2.vm.box = "centos/7"
    srvelk2.vm.network "private_network", type: "dhcp"
    srvelk2.vm.hostname = "srv-elk2"
    srvelk2.vm.provider "virtualbox" do |v|
      v.name = "srv-elk2"
      v.memory = 2048
      v.cpus = 2
    end
    
    config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
    service sshd restart
  SHELL

end

end
