# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/centos7"  #configuration du VM -> image geerlingguy/centos7"

  config.ssh.insert_key = false #

  config.vm.synced_folder ".", "/vagrant", disabled: true #desactivé le dossier sychronisation

  config.vm.provider :virtualbox do |v|
    v.memory = 256 # ram 256 mg
    v.linked_clone = true

  end

# App serveur 1
  config.vm.define "app1" do |app|
    app.vm.hostname = "orc-app1.test"
    app.vm.network :private_network, ip: "192.168.60.4"

  end

# App serveur 2
  config.vm.define "app2" do |app|
    app.vm.hostname = "orc-app2.test"
    app.vm.network :private_network, ip: "192.168.60.5"

  end

# App serveur 3
  config.vm.define "db" do |db|
    db.vm.hostname = "orc-db.test"
    db.vm.network :private_network, ip: "192.168.60.6"

  end
end