---
- hosts: solr
  become: true

  vars_files:
    - vars.yml
  
  pre_tasks:
    - name : besoin de mise en jour
      apt: update_cache=true cahe_valid_time=3600

  handlers:
    - name: restart solr
      service: name=solr state=restarted
  tasks:
    - name: install Java
      apt: name=openjdk-8-jdk state=present

    - name: telecharger Solr
      get_url:
        url: "https://www.apache.org/dyn/closer.lua/lucene/solr/{{ solr_version }}/{{ solr_version }}.tgz?action=download"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        chechsum: "{{ solr_checksum }}"

    - name: Expand Solr
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

    - name: run solr installation script.
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{ solr_dir }}/bin/solr

    - name: Ensure solr est start et tjrs start au demarrage
      service: name=solr state=strated enabled=yes

      notify: restart apache